### ISSUE TITLE
Improve Failed Authentication Message

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.DataSource.Polygon#16]
#### Expected Behavior
The following message:

> Failed to authenticate websocket. Make sure your API key is valid and has the right permissions.

included the information about the permission. For example, if we don't have permission to subscribe to equity, this information would prompt the user to remove equity from their algorithm.

#### Potential Solution
Add the name of the symbol we tried to subscribe to and failed.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Moving to handle this here: https://github.com/QuantConnect/Lean/issues/8037
